# ----------------------------------------------------------------
# Configuration file for http://travis-ci.org/#!/chdorner/epubinfo
# ----------------------------------------------------------------

language: ruby
script: "bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - ruby-head
  - jruby-head

before_install:
  - gem install bundler

